### ISSUE TITLE
doesn't work anymore?

### ISSUE THREAD

**Issue by felixsanz** [josestg/rehype-figure#1]

**Comment by devgioele** [comment]
It is working for me when using it as a Markdown plugin with [astro](astro.build). May be you have a conflict between plugins? The order how plugins are applied does matter!
E.g. I had to first apply `rehype-figure` and only then `rehype-picture`.

**Comment by felixsanz** [comment]
not completed. it doesn't work

**Comment by deadcoder0904** [comment]
can confirm, it didn't work for me either (order was correct) so i checked out [rehype-picture](https://github.com/rehypejs/rehype-picture/blob/main/index.js) & it has much simpler code.

it is similar too so i wrote my own little snippet that works perfectly:

```ts
.use(() => (tree) => {
    visit(tree, 'element', (node, index, parent) => {
      if (node.tagName === 'img') {
        parent.children[index] = h('figure', [
          h('img', { ...node.properties }),
          h('figcaption', node.properties.alt),
        ])
      }
    })
  })
```
